version: "2"
plugins:
  shellcheck:
    enabled: true
    checks:
      SC1090:
        enabled: false
      SC1091:
        enabled: false
  markdownlint:
    enabled: true
    checks:
      MD009:
        enabled: false
      MD013:
        enabled: false
      MD034:
        enabled: false
      MD036:
        enabled: false
